# Generated by Django 4.2.5 on 2024-01-21 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devicedash.brands')),
            ],
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/phones/')),
                ('quick_spec', models.JSONField(blank=True, null=True)),
                ('detail_spec', models.JSONField(blank=True, null=True)),
                ('pricing', models.JSONField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devicedash.phones')),
            ],
        ),
    ]
