# Generated by Django 4.2.5 on 2024-01-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicedash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phones',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='specifications',
            old_name='device_id',
            new_name='device',
        ),
    ]
