# Generated by Django 4.2.5 on 2024-01-25 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devicedash', '0002_rename_brand_id_phones_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specifications',
            name='detail_spec',
        ),
        migrations.AlterField(
            model_name='specifications',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devicedash.phones'),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='img',
            field=models.CharField(max_length=255),
        ),
    ]
