# Generated by Django 4.2.5 on 2024-02-02 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devicedash', '0003_remove_specifications_detail_spec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devicedash.brands')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devicedash.phones')),
            ],
        ),
    ]
