# Generated by Django 4.2.5 on 2024-02-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedash', '0004_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
